---
title: "Program_assignment2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(ggplot2)
```

# R Markdown

First we set the different parameters for the study: the rate parameter, the number of random variables per simulation and the number of simulation

```{r setup-parameters}
lambda <- 0.2
n <- 40
nb_simu <- 1000
```

We calculate now the mean of `r nb_simu` of `r n` random variables simulated according to a exponential distribution with a rate parameter equals to `r lambda` and display its distribution.

```{r means-simu}
means_simu <- data.frame(mean = replicate(nb_simu, mean(rexp(n, lambda))))
```

```{r theoric-mean-sd, echo = FALSE}
theoric_mean <- 1/lambda
theoric_sd <- (1/lambda)/sqrt(n)
```

```{r plot-distribution, echo=FALSE}
ggplot(means_simu, aes(x=mean)) +
  geom_histogram(aes(y=..density..), binwidth=.1, colour="gold", fill="gold2") +
  geom_line(aes(y = ..density.., colour = 'Empirical'), stat = 'density', size = 1) +
  geom_vline(aes(xintercept=mean(mean, na.rm=TRUE)),
             color="red", linetype="dashed", size=1) +
  stat_function(fun = dnorm, aes(colour = 'Theoritical'), args = c(mean=theoric_mean, sd = theoric_sd), size = 1) +
  scale_colour_manual(values=c("red", "blue"), name="Densities") +
  ylab("Density") + xlab("z") + ggtitle("Mean values distribution") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r compare-theoric-empirc, echo = FALSE}
result = data.frame(mean = c(mean(means_simu$mean), theoric_mean), standard_deviatation = c(sd(means_simu$mean), theoric_sd), variance = c(sd(means_simu$mean)^2, theoric_sd^2))
colnames(result) = c("Mean", "Standard Deviation", "Variance")
row.names(result) = c("Empirical", "Theoric")
```

```{r display-table, echo = FALSE, results = 'asis'}
kable(result, caption = "Comparison Theoric vs. Empiric")
```